sudo: false
language: python
dist: xenial  # Ubuntu 16, required for Python 3.7+
python:
    - "2.7"
#    - "3.3"  # End-of-life September 2017
    - "3.4"
    - "3.5"
    - "3.6"
    - "3.7"
install:
  - pip install tox-travis
  - pip install flake8
script:
  - tox
#  - flake8 .  # Now part of tox.ini
